version: "3"
services:
  nginx-proxy:
    image: nginx:alpine
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx.conf:/etc/nginx/nginx.conf:ro
      - certs/server-cert.pem:/etc/nginx/ssl/nginx.crt
      - certs/server-key.pem:/etc/nginx/ssl/nginx.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  nexus:
    image: sonatype/nexus3
    volumes:
      - data:/nexus-data
    networks:
      - net
networks:
  net:
    driver: overlay
volumes:
  data:
    driver: "rexray"


